spring:

  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-demo?useSSL=false
    username: root
    password: hello1234
    driver-class-name: com.mysql.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

mybatis:
  type-aliases-package: org.htnecro.demo.meta
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.htnecro.demo.typehandler.IntValueEnumTypeHandler
