spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-demo?useSSL=false
    username: root
    password: hello1234
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      initial-size: 10
      max-active: 20
      min-idle: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 3000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall,log4j2